/** CRDMO 最小可运行示例包：本地校验预览用，导入时走服务端 validate */
export const CRDMO_SAMPLE_PACK = {
  packId: "crdmo-mainline-v1",
  name: "核药CRDMO项目主线",
  version: "1.0.0",
  artifactDefinitions: [
    {
      slug: "crdmo_scope_brief",
      name: "项目建设边界说明",
      artifactType: "document",
      stage: "INITIATION",
      description: "明确 CRDMO 项目用地边界、建设规模与分期建设范围。",
      defaultStatus: "draft",
      allowedStatuses: [
        { status: "draft", label: "草稿" },
        { status: "confirmed", label: "已确认" },
      ],
      enabled: true,
    },
  ],
  areas: [],
  mapLocations: [
    {
      slug: "loc_crdmo_project_office",
      name: "医养公司项目办公室",
      sandtableRegionId: "command_center",
      sandtableZoneId: "command_meeting",
      type: "project_office",
      group: "项目部",
      category: "project_team",
      description: "医养公司 CRDMO 项目部日常协调与边界确认办理地点。",
      unlockStage: "INITIATION",
      relatedNpcNames: ["项目分管领导", "设计单位负责人"],
      enabled: true,
    },
    {
      slug: "loc_natural_resources_bureau",
      name: "市自然资源和规划局",
      sandtableRegionId: "approval_regulatory",
      sandtableZoneId: "approval_window",
      type: "government",
      group: "政府单位",
      category: "government",
      description: "规划条件预检、用地规划许可与审批补正对接窗口。",
      unlockStage: "APPROVAL",
      relatedNpcNames: ["自规局经办人"],
      enabled: true,
    },
  ],
  npcs: [
    {
      slug: "npc_crdmo_leader",
      name: "项目分管领导",
      title: "医养公司项目分管领导",
      type: "owner",
      category: "owner_regulator",
      level: "S",
      faction: "owner",
      description: "统筹 CRDMO 项目边界确认与跨部门协调。",
      helpsWith: ["确认建设边界", "组织专题协调会"],
      riskTags: ["决策节奏", "边界争议"],
      quotes: ["先把边界说清楚，后面才不会反复改。"],
      defaultRelation: 55,
      enabled: true,
    },
    {
      slug: "npc_design_lead",
      name: "设计单位负责人",
      title: "设计总负责人",
      type: "design",
      category: "design_supply",
      level: "A",
      faction: "consultant",
      description: "负责方案与边界图纸核对，支撑边界说明编制。",
      helpsWith: ["核对用地红线", "补充边界图纸"],
      defaultRelation: 50,
      enabled: true,
    },
    {
      slug: "npc_planning_officer",
      name: "自规局经办人",
      title: "规划科经办人",
      type: "regulator",
      category: "owner_regulator",
      level: "A",
      faction: "government",
      description: "受理规划预检材料，反馈补正意见。",
      blocksWhen: ["边界说明未确认", "材料不完整"],
      defaultRelation: 45,
      enabled: true,
    },
  ],
  storyEntries: [
    {
      slug: "story_crdmo_scope_confirm",
      title: "确认 CRDMO 建设边界",
      storyType: "task_story",
      status: "published",
      inkFile: "clarify_contract_boundary",
      stage: "INITIATION",
      relatedTaskSlugs: ["task_crdmo_scope_confirm"],
      relatedNpcNames: ["项目分管领导", "设计单位负责人"],
      previewText: "与设计、业主共同核对 CRDMO 项目建设边界并形成说明。",
      enabled: true,
    },
  ],
  taskTemplates: [
    {
      slug: "task_crdmo_scope_confirm",
      title: "确认 CRDMO 建设边界",
      description: "组织设计单位与业主核对用地边界，形成《项目建设边界说明》。",
      category: "mainline",
      stage: "INITIATION",
      area: "项目管理",
      rarity: "R",
      inkFile: "clarify_contract_boundary",
      storySlug: "story_crdmo_scope_confirm",
      npcList: ["项目分管领导", "设计单位负责人"],
      outputArtifacts: [{ artifactSlug: "crdmo_scope_brief", status: "confirmed" }],
      milestoneEffectList: [{ milestone: "projectOrgDone", value: true }],
      enabled: true,
    },
    {
      slug: "task_cro_planning_precheck",
      title: "规划预检材料提交",
      description: "向自规局提交规划预检材料，推进规划条件对接。",
      category: "mainline",
      stage: "APPROVAL",
      area: "项目管理",
      rarity: "SR",
      inkFile: "confirm_planning_condition",
      npcList: ["自规局经办人"],
      prerequisiteTaskSlugs: ["task_crdmo_scope_confirm"],
      inputArtifacts: [{ artifactSlug: "crdmo_scope_brief", minStatus: "confirmed" }],
      enabled: true,
    },
  ],
  eventTemplates: [
    {
      slug: "event_planning_feedback_revision",
      title: "规划条件补正反馈",
      description: "自规局反馈规划预检补正意见，需补充边界说明或图纸。",
      category: "correction",
      rarity: "R",
      inkFile: "project_correction_task",
      storySlug: "story_crdmo_scope_confirm",
      triggerTaskSlugs: ["task_cro_planning_precheck"],
      taskEffects: [{ action: "spawn", taskSlug: "task_cro_planning_precheck" }],
      npcList: ["自规局经办人"],
      weight: 12,
      enabled: true,
    },
  ],
  locationActions: [
    {
      slug: "action_confirm_crdmo_scope",
      label: "确认项目建设边界",
      description: "在项目办公室与设计、业主核对边界并生成边界说明任务。",
      locationSlug: "loc_crdmo_project_office",
      unlockStage: "INITIATION",
      triggerTaskSlugs: ["task_crdmo_scope_confirm"],
      relatedNpcNames: ["项目分管领导"],
      resultText: "已发起 CRDMO 建设边界确认任务。",
      sortOrder: 1,
      enabled: true,
    },
  ],
};

export const CRDMO_SAMPLE_PACK_JSON = JSON.stringify(CRDMO_SAMPLE_PACK, null, 2);
